### ISSUE TITLE
열거형 타입으로 지정하는 것이 문자열 타입으로 지정했을때와 비교해 얻을 수 있는 효과를 설명하세요

### ISSUE THREAD

**Issue by frogk** [deep-dive-everything/typescript-with-react#11]
📚 94p - 97p
📌 열거형 타입으로 지정하는 것이 문자열 타입으로 지정했을때와 비교해 얻을 수 있는 효과를 설명하세요

**Comment by hotdog1004** [comment]
열거형은 관련이 높은 멤버를 모아 문자열 상수처럼 사용하고자 할 때 유용하게 쓸 수 있다.
열거형 타입으로 지정한 경우 문자열 타입으로 지정한 것과 비교했을 때 얻을 수 있는 효과는 아래와 같다.
1. 타입안정성
- 열거형 타입에 명시되지 않은 다른 문자열은 인자로 받을 수 없어 타입 안정성이 우수하다.
2. 명확한 의미 전달과 높은 응집력
- 열거형 타입에서 다루는 값이 무엇인지 명확하다. 해당 타입에 대한 값이 모여있기 때문에 응집력 또한 뛰어나다.
3. 가독성
- 열거형 멤버를 통해 어떤 상태를 나타내는지 쉽게 이해할 수 있다.

**Comment by kwonhygge** [comment]
열거형 타입으로 지정했을 때의 장점은 아래와 같습니다.
1. 타입안정성: 타입에 명시되지 않은 다른 문자열은 인자로 받을 수 없어 타입 안전성이 우수합니다.
2. 명확한 의미 전달과 높은 응집력: 타입이 다루는 값이 무엇인지 명확하고 타입에 관한 값을 모아놓은 것으로 응집력이 우수합니다.
3. 가독성: 응집도가 높기 때문에 말하고자 하는 바가 더욱 명확합니다. 열거형 멤버를 통해 어떤 상태를 나타내는지 쉽게 알 수 있습니다.

**Comment by limejin** [comment]
타입 안전성, 명확한 의미 전달과 높은 응집력, 가독성 효과를 얻을 수 있습니다. 관련이 높은 멤버를 모아 문자열 상수처럼 사용하고자 할 때 유용합니다.

**Comment by samseburn** [comment]
열거형 타입으로 지정했을 때, 타입 안전성, 코드 가독성, 그리고 응집력 면에서 장점이 있습니다. 
또한, 자동으로 완성되기 때문에 문자열 타입보다 오타로부터 안전한 것도 소소한 장점이라고 생각합니다.
