### ISSUE TITLE
Universal1, 2 타입이 충족되는 경우를 각각 골라주세요.

### ISSUE THREAD

**Issue by limejin** [deep-dive-everything/typescript-with-react#12]
📚 122p - 126p
📌 Universal1, 2 타입이 충족되는 경우를 각각 골라주세요.
```
type IdType = string | number;
type Numeric = number | boolean;

type Universal1 = IdType & Numeric;
type Universal2 = IdType | Numeric;
```

1. string이면서 number인 경우
2. string이면서 boolean인 경우
3. number이면서 number인 경우
4. number이면서 boolean인 경우

**Comment by kwonhygge** [comment]
Universal1의 경우엔 3번의 경우가 충족됩니다. 교차 타입은 두 타입을 모두 만족하는 경우에 유효하기 때문입니다.
Universal2의 경우 모든 경우가 충족됩니다. 유니온 타입은 어느 한쪽이라도 충족하면 가능하기 때문입니다.

**Comment by frogk** [comment]
- Universal1
  3번이 해당합니다. IdType과 Numeric의 교차티입이므로 두 타입을 모두 만족해야합니다. string | number와 number | boolean의 교집합을 의미하므로 number이면서 number인 3번이 올바른 선택지 입니다.

- Universal 2
  1, 2, 3, 4 모두 해당합니다. 유니온 타입은 IdType과 Numeric의 합집합을 의미하므로 string, number, boolean이 모두 해당합니다.

**Comment by hotdog1004** [comment]
Universal1은 3번 경우에 해당됩니다. Universal1은 IdType과 Numeric의 교차타입이기 때문입니다.
Universal2은 모든 경우에 해당됩니다. Universal2은  IdType과 Numeric의 유니온 타입이기 때문입니다.

**Comment by limejin** [comment]
Universal1 - 3번
Universal2 - 1,2,3,4 번

**Comment by samseburn** [comment]
- `Universal1` 타입 - `number`
- `Universal2` 타입 - `string | number | boolean`
