### ISSUE TITLE
다음 코드에서 발생하는 문제점은 무엇이며, 이를 해결하기 위해 사용할 수 있는 타입스크립트 기능은 무엇인가요?

### ISSUE THREAD

**Issue by kwonhygge** [deep-dive-everything/typescript-with-react#17]
📚 174p - 175p
📌 다음 코드에서 발생하는 문제점은 무엇이며, 이를 해결하기 위해 사용할 수 있는 타입스크립트 기능은 무엇인가요?

```ts
const colors = {
  red: '#F45452',
  green: '#0C952A',
  blue: '#1A7CFF'
};

const getColorHex = (key: string) => colors[key];
```

**Comment by kwonhygge** [comment]
인자인 key의 타입이 string으로 되어있기 때문에 어떤 값이든 들어갈 수 있고 정의되어있지 않은 값을 키로 넣어 예상치 못한 동작을 할 수도 있습니다.

이를 방지하기 위해 colors를 불변 객체로 선언하고 keyof 연산자를 사용해 불변객체타입을 만들어 사용할 수 있습니다.
```ts
const colors = {
  red: '#F45452',
  green: '#0C952A',
  blue: '#1A7CFF'
} as const; // 'as const'를 사용하여 객체를 불변으로 만듭니다.

type Colors = keyof typeof colors; // colors 객체의 키들로 구성된 타입을 생성

const getColorHex = (key: Colors) => colors[key];
```

**Comment by hotdog1004** [comment]
colors에 어떤 값이 추가될지 모르기 때문에 함수의 반환값은 any가 됩니다. 
위와 같은 문제를 해결하기 위해 as const 키워드로 객체를 불변 객체로 선언하고, keyof 연산자를 사용해서 gotColorHex 함수 인자로 실제 colors 객체에 존재하는 키값만 받도록 설정할 수 있습니다.

**Comment by samseburn** [comment]
- 인자의 key 타입이 string으로 되어 있어 어떤 값이든 들어갈 수 있습니다. 만약 객체 `colors`에 정의되지 않은 키가 들어가게 된다면 예상치 못한 반환값이 출력될 수 있습니다.
- 해결방법
  - `as const`로 불변 객체 정의
  - `keyof typeof colors`로 객체의 키 값만을 인자로 받게 변경 
```ts
const colors = {
  red: '#F45452',
  green: '#0C952A',
  blue: '#1A7CFF'
} as const

const getColorHex = (key: keyof typeof colors) => colors[key]
```

**Comment by frogk** [comment]
1. 키 타입을 해당 객체에 존재하는 키값으로 설정하는 것이 아니라 string으로 설정하면 color에 어떤 값이 추가될 지 모르기 때문에 getColorHex 함수의 값은 any가 됨
2. 불변객체. as const 키워드로 객체를 불변 객체로 선언하고, keyof 연산자를 사용해 getColorHex함수 인자로 실제 colors객체에 존재하는 키값만 받도록 설정. 타입 구체적으로 설정함.

**Comment by limejin** [comment]
함수 파라미터 key가 모든 문자열을 허용하게 되어 colors 객체에 없는 키가 전달될 수 있습니다. 정의되지 않은 키에 접근하면 undefined가 반환될 가능이 있습니다. 이러한 문제점은 타입 안전성을 해치고 런타입 시, 오류가 발생할 수 있습니다.
`keyof `연산자를 활용하여 colors 객체의 키만 허용하는 타입을 만들 수 있습니다.
