### ISSUE TITLE
식별할 수 있는 유니온의 판별자 선정

### ISSUE THREAD

**Issue by frogk** [deep-dive-everything/typescript-with-react#18]
📚 143p
📌 식별할 수 있는 유니온의 판별자로 사용할 수 있는 타입은 무엇인지 설명하세요.

**Comment by frogk** [comment]
- 리터럴 타입이어야 한다.
-  판별자로 선정한 값에 적어도 하나 이상의 유닛 타입이 포함되어야 하며 인스턴스화 할 수 있는 타입은 포함되지 않아야 한다.

유닛 타입은 다른 타입으로 쪼개지지 않고 오직 하나의 정확한 값을 나타내는 타입을 말한다. 다양한 타입을 할당할 수 있는 void, string, number같은 타입은 이에 해당하지 않는다.

**Comment by hotdog1004** [comment]
타입스크립트는 식별할 수 있는 유니온의 판별자로 사용할 수 있는 타입에 대해 아래와 같이 정의하고 있습니다.
- 리터럴 타입이어야한다.
- 판별자로 선정한 값에 적어도 하나 이상의 유닛 타입이 포함되어야하며, 인스턴스화 할 수 있는 타입은 포함되지 않아야한다.

**Comment by limejin** [comment]
다른 타입으로 쪼개지지 않고 오직 하나의 값을 가지는, 유니타입(null, undefined, 리터럴 타입, true, 1 등)으로 선언되어야 정상적으로 동작합니다.

**Comment by samseburn** [comment]
null, undefined, 리터럴 타입을 비롷새 true, 1 등 정확한 값을 나타내는 유닛 타입으로 선언되어야 원하는 동작을 기대할 수 있습니다.
