### ISSUE TITLE
type과 interface의 공통점과 차이점

### ISSUE THREAD

**Issue by hotdog1004** [deep-dive-everything/typescript-with-react#2]
📚 74p - 75
📌 타입스크립트의 type과 inferface 키워드의 공통점과 차이점에 대해 설명해주세요.

**Comment by hotdog1004** [comment]
### 공통점
- 객체와 함수의 타입을 정의해서 사용할 수 있다.
- 타입 확장이 가능하다.

### 차이점
- type은 타입 선언시 computed property name의 사용이 가능하다.

  >  `computed property name`
  표현식을 이용해서 객체의 key 값을 정의하는 문법

- interface는 선언적 확장이 가능하다.

  > interface의 경우 같은 이름의 객체를 다시 한번 선언하면 자동으로 확장 되지만 type은 불가능

**Comment by kwonhygge** [comment]
확장 방법:
   - interface는 다른 인터페이스를 상속할 때 extends를 사용하여 확장할 수 있습니다.
   - type은 &연산자를 사용하여 다른 타입과 결합할 수 있습니다.

사용 영역:
   - interface는 주로 객체 타입을 정의하는 데 사용되며, 클래스의 타입으로 사용하거나 확장성이 필요할 때 많이 사용합니다.
   - type은 객체, 유니언, 튜플 등 다양한 타입을 정의하는 데 사용할 수 있어 더 유연하게 사용될 수 있습니다.

선언 병합:
   - interface는 동일한 이름의 인터페이스를 여러 번 선언하면 병합됩니다
   - type은 동일한 이름을 여러 번 선언할 수 없고 병합되지 않습니다

**Comment by limejin** [comment]
공통점 : 객체 타입 정의 가능
차이점 : type 정의에서만 쓸 수 있는 기능 존재 (유니온 타입, 교차 타입 등), type 재선언 불가능 / interface 재선언 가능 (확장)

**Comment by devsomda** [comment]
공통점: type과 interface 모두 객체, 함수, 배열 등의 타입을 정의할 수 있으며, 타입스크립트에서 타입을 지정하는 데 사용됩니다.
차이점: interface는 선언 병합이 가능하지만, type은 불가능하며, type은 유니온 타입과 같은 더 복잡한 타입을 정의할 수 있는 반면, interface는 객체 형태에 중점을 둡니다.
