### ISSUE TITLE
타입스크립트의 컴파일 과정에 대해 순서대로 설명하세요.

### ISSUE THREAD

**Issue by hotdog1004** [deep-dive-everything/typescript-with-react#22]
📚 198p
📌 타입스크립트의 컴파일 과정에 대해 순서대로 설명하세요.

**Comment by hotdog1004** [comment]
타입스크립트 컴파일러는 다섯 단계를 거쳐 타입 검사와 자바스크립트 소스 변환을 진행합니다.
스캐너 -> 파서 -> 바인더 -> 체커 -> 이미터

타입스크립트의 컴파일 과정은 아래와 같습니다.
1. tsc 명령어를 실행하여 프로그램 객체가 컴파일 과정을 시작
2. 스캐너가 소스 파일을 토큰 단위로 분리
3. 파서는 토큰을 이용해서 AST를 생성
4. 바인더는 AST의 각 노드에 대응하는 심볼을 생성(심볼은 선언된 타입의 노드 정보를 담고 있음)
5. 체커는 AST를 탐색하며 심볼 정보를 통해 타입 검사를 수행
6. 타입 검사 결과 에러가 없다면 이미터를 사용해서 자바스크립트 소스 파일로 변환

**Comment by kwonhygge** [comment]
타입스크립트 컴파일 과정은 아래와 같습니다.
1. tsc 명령어를 실행하여 프로그램 객체가 컴파일 과정을 시작
2. 스캐너가 소스 파일을 토큰 단위로 분리
3. 파서가 토큰을 이용해 AST 생성
4. 바인더가 AST의 각 노드에 대응하는 심볼을 생성
5. 체커가 AST를 탐색하며 심볼 정보를 활용하여 타입검사 수행
6. 타입 검사 결과 에러가 없다면 이미터를 사용해서 자바스크립트 소스 파일로 변환

**Comment by devsomda** [comment]
1. tsc 명령어를 통해 컴파일 과정 시작 (프로그램 객체)
2. 소스 파일을 토큰 단위로 분리 (스캐너)
3. 토큰을 이용해 AST 생성 (파서)
4. AST 각 노드에 대응하는 심볼 생성 (바인더)
5. AST를 탐색하며 심볼 정보를 활용해 타입 검사 수행 (체커)
6. 에러가 없다면 자바스크립트 소스 파일로 변환 (이미터)

**Comment by samseburn** [comment]
타입스크립트 컴파일 과정은 다음과 같이 진행됩니다.

- 프로그램 객체: 프로그램 객체가 tsc 명령어를 통해 컴파일 과정을 시작합니다.
- 스캐너: 소스 파일을 읽어들여 토큰 단위로 분리합니다.
- 파서: 토큰을 바탕으로 추상 구문 트리인 AST를 생성합니다.
- 바인더: AST의 각 노드에 대응하는 심볼을 생성하여, 심볼에 타입 정보를 담습니다.
- 체커: AST를 탐색하며 심볼 정보를 이용해 타입 검사를 수행합니다.
- 이미터: 타입 검사 결과 오류가 없다면, 자바스크립트 소스 파일로 변환하여 출력합니다.
