### ISSUE TITLE
tsc와 바벨의 공통점과 차이점

### ISSUE THREAD

**Issue by frogk** [deep-dive-everything/typescript-with-react#24]
📚 191p
📌 타입스크립트 컴파일러와 바벨이 어떤 역할을 하는지 간단하게 설명하고 둘의 공통점과 차이점을 설명하세요.

**Comment by hotdog1004** [comment]
tsc는 타입스크립트 컴파일러를 뜻합니다.
바벨은 자바스크립트 컴파일러로 ECMAScript 2015 이후의 코드를 현재 혹은 오래된 브라우저와 호환되는 버전으로 변환해주는 역할을 합니다.

### 공통점
둘다 소스코드를 ES5 이하의 자바스크립트 코드로 컴파일해주는 역할을 합니다.

### 차이점
tsc는 컴파일과 타입 검사를 진행하지만, 바벨은 최신 버전의 자바스크립트 코드를 낮은 버전으로 컴파일하는 것이 주된 역할입니다.

**Comment by kwonhygge** [comment]
타입스크립트 컴파일러와 바벨은 코드를 모든 브라우저에 호환되는 언어로 바꾸어준다는 공통점을 가지고 있습니다.
다만 타입스크립트 컴파일러는 타입 체크를 해준다는 것이 차이점입니다.

**Comment by devsomda** [comment]
tsc와 바벨은 모두 소스코드를 하위 버전과 호환되는 코드로 컴파일 해준다
하지만 tsc와 달리 바벨은 타입 검사를 하지 않는다.

**Comment by samseburn** [comment]
#### 타입스크립트 컴파일러와 바벨
- 타입스크립트 컴파일러: 타입스크립트 코드를 자바스크립트로 변환하고, 타입 검사를 통해 코드의 타입 안정성을 확인합니다.
- 바벨: 최신 JavaScript 문법을 하위 버전으로 변환해주며, 주로 문법 변환 목적으로 사용합니다.
#### 타입스크립트 컴파일러 vs 바벨
- 공통점: 둘 다 코드를 변환하여 실행 가능한 자바스크립트 파일 생성
- 차이점: 타입스트립트 컴파일러는 타입 검사 작업도 수행하지만, 바벨은 타입 검사 없이 문법 변환만 수행합니다.
