### ISSUE TITLE
타입스크립트 컴파일러 실행 과정은?

### ISSUE THREAD

**Issue by devsomda** [deep-dive-everything/typescript-with-react#26]
📚 192p
📌 타입스크립트 컴파일러 실행 과정은? 5단계로 간략히 적어주세요.

**Comment by hotdog1004** [comment]
타입스크립트 컴파일러는 다섯 단계를 거쳐 타입 검사와 자바스크립트 소스 변환을 진행합니다.

1. 스캐너 
   :  타입스크립트 소스 파일을 어휘적으로 분석하여 토큰을 생성합니다.
2. 파서
   :  생성된 토큰 정보를 기반으로 AST를 생성합니다.
3. 바인더
   :  AST의 각 노드에 대응하는 심볼을 생성합니다.
4. 체커
   :  AST를 탐색하면서 심볼 정보를 통해 타입 검사를 수행합니다.
5. 이미터
   :  AST와 코드 검사를 기반으로하여 자바스크립트 소스 파일로 변환합니다.

**Comment by kwonhygge** [comment]
1. 스캐너: 소스파일을 분석하여 토큰 생성
2. 파서: 생성된 토큰을 기반으로 AST 생성
3. 바인더: AST의 각 노드에 대응하는 심볼 생성
4. 체커: AST를 탐색하며 심볼 정보를 통해 타입검사 수행
5. 이미터: 타입검사 결과 에러가 없으면 자바스크립트 소스 파일로 변환

**Comment by samseburn** [comment]
타입스크립트 컴파일 과정은 다음과 같이 진행됩니다.

- 스캐너: 소스 파일을 읽어들여 토큰 단위로 분리합니다.
- 파서: 토큰을 바탕으로 추상 구문 트리인 AST를 생성합니다.
- 바인더: AST의 각 노드에 대응하는 심볼을 생성하여, 심볼에 타입 정보를 담습니다.
- 체커: AST를 탐색하며 심볼 정보를 이용해 타입 검사를 수행합니다.
- 이미터: 타입 검사 결과 오류가 없다면, 자바스크립트 소스 파일로 변환하여 출력합니다.
