### ISSUE TITLE
런타임과 컴파일 타임에 대해 설명해주세요.

### ISSUE THREAD

**Issue by limejin** [deep-dive-everything/typescript-with-react#27]
📚 184p
📌 런타임과 컴파일 타임에 대해 차이점을 중심으로 설명해주세요.

**Comment by hotdog1004** [comment]
### 컴파일 타임
소스코드가 컴파일 과정을 거쳐 컴퓨터가 인식할 수 있는 기계어 코드(바이트 코드)로 변환되어 실행할 수 있는 프로그램이 되는 과정
### 런타임
소스코드의 컴파일이 완료된 후 프로그램이 메모리에 적재되어 실행되는 시간

**Comment by kwonhygge** [comment]
컴파일 타임: 소스코드가 기계어 코드로 변환되어 실행이 가능한 프로그램이 되는 과정
런타임: 컴파일된 프로그램이 메모리에 적재되어 실행이 되는 시간

**Comment by devsomda** [comment]
컴파일 타임: 소스코드가 컴퓨터가 인식할 수 있는 바이트 코드로 변환됨
런타임: 프로그램이 실행되는 환경.

**Comment by samseburn** [comment]
- 컴파일 타임: 프로그램이 실행 가능하도록 변환되고 오류가 검출되는 단계.
- 런타임: 컴파일된 프로그램이 메모리에 로드되어 실행되며, 실행 중 오류가 발생할 수 있는 단계.
