### ISSUE TITLE
타입스크립트 컴파일 과정에서 AST는 어떻게 생성되며, AST를 생성하는 이유는 무엇인가요?

### ISSUE THREAD

**Issue by samseburn** [deep-dive-everything/typescript-with-react#28]
📚 NNp - NNp
📌 타입스크립트에서 AST는 어떻게 생성되며, AST를 생성하는 이유는 무엇인가요?

**Comment by hotdog1004** [comment]
AST는 컴파일러가 동작하는 데 핵심 기반이 되는 자료 구조로 소스코드의 구조를 트리 형태로 표현합니다.
타입스크립트의 컴파일 과정 중 파서 단계에서 스캐너가 소스 파일을 토큰으로 나눠준 정보를 이용해서 AST를 생성합니다. 
그리고 체커 단계에서 AST를 통해 타입 검사를 진행합니다. 이런 과정 덕분에 타입스크립트는 컴파일 시점에서 타입을 정적으로 추론할 수 있습니다.

**Comment by kwonhygge** [comment]
AST를 생성하는 주된 이유는 타입스크립트가 AST를 활용하여 타입검사를 수행하기 때문입니다.
타입스크립트 파서는 이전 단계에서 생성된 토큰을 기반으로 코드의 실질적인 구조를 노드 단위의 트리로 생성합니다.
이때 구문적 분석을 통해 해당 토큰의 종류를 판별하고 코드상의 위치와 내용과 같은 추가 정보를 담게됩니다.

**Comment by devsomda** [comment]
AST는 tsc가 동작하는데(타입 검사를 수행하는 데) 핵심이 되는 자료구조이다.
파서는 스캐너가 생성한 토큰을 기반으로 AST를 생성한다.
