### ISSUE TITLE
API 상태 관리를 위해 책에서 소개된 두가지 방법 각각의 특징을 이야기해주세요

### ISSUE THREAD

**Issue by kwonhygge** [deep-dive-everything/typescript-with-react#29]
📚 218p - 223p
📌 API 상태 관리를 위해 책에서 소개된 두가지 방법 각각의 특징을 이야기해주세요.

**Comment by kwonhygge** [comment]
첫번째는 전역 상태관리 라이브러리를 사용하는 것입니다. 이 방법은 한곳에 API 상태를 저장해놓고 원하는 곳에서 마음껏 가져다쓰는 방법입니다. 전역 상태관리 라이브러리를 사용하면 복잡한 컴포넌트 구조속에서도 props drilling 없이 API 상태를 전달할 수 있습니다. 
하지만 API가 많아질수록 관련된 스토어나 상태가 계속 늘어납니다. 만약 2개 이상의 컴포넌트가 구독하고 있는 비동기 상태가 있다면 쓸데없는 비동기 통신이 발생하거나 의도치 않은 상태 변경이 발생할 수 있습니다.

두번째는 react-query 라이브러리처럼 훅으로 호출하는 방법입니다. 이 방법은 캐시를 사용하여 비동기 함수를 호출하며, 상태 관리 라이브러리를 사용하여 발생했던 의도치 않은 상태변경을 방지합니다.

**Comment by hotdog1004** [comment]
API 상태를 관리하는 방법으로 상태 관리 라이브러리를 사용하는 것과 react-qurey나 useSwr 같은 훅을 사용하는 방법이 있습니다. 

상태 관리 라이브러리를 사용하는 방법은 비동기 처리 함수를 호출하기 위해 액션이 추가될 때마다 관련된 스토어나 상태가 계속 늘어나게 됩니다. 그리고 전역 상태 관리자가 모든 비동기 상태에 접근하고 변경할 수 있기 때문에 만약 2개 이상의 컴포넌트가 구독하고 있는 비동기 상태가 있다면 쓸데없는 비동기 통신이 발생하거나 의도치 않은 상태 변경이 발생할 수 있습니다.

react-query나 useSwr 같은 훅을 사용하는 방법은 상태 변경 라이브러리를 사용한 방식보다 훨씬 간단합니다. 훅은 캐시를 사용하여 비동기 함수를 호출하며 상태관리 라이브러리에서 발생했던 의도치 않은 상태 변경을 방지할 수 있습니다.

**Comment by devsomda** [comment]
1. 상태 관리 라이브러리
비동기 처리 함수 호출을 위한 액션이 추가될 때마다 관련 스토어 혹은 상태가 계속 늘어남. 이로 인해 전역 상태 관리자가 모든 비동기 상태에 접근하고 변경할 수 있어 의도치 않은 상태 변경이 발생할 수 있다.

2. 훅 사용 (react-query, useSwr 등)
캐시를 사용해 비동기 함수를 호출해 의도치 않은 상태 변경을 방지한다. 또한 일반적 훅을 호출하듯 사용할 수 있다.

**Comment by limejin** [comment]
1. 상태관리 라이브러리에서 호출하기 : 서비스 코드를 사용해서 비동기 상태를 변화시킬 수 있는 함수를 제공한다. 컴포넌트는 이러한 함수를 사용하여 상태를 구독하며, 상태가 변경될 때, 컴포넌트를 재랜더링하는 방식이다. 이러한 방식의 문제점은 비동기 처리함수를 호출하기 위해 액션이 추가될떄마다 관련된 스토어나 상태가 계속 늘어나며 이로인해 쓸데없는 비동기 통신이 발생할 가능성이 높아진다는 점이 있다.
2. 훅으로 호출하기 : 캐시를 사용하여 비동기 함수를 호출하여 상태관리 라이브러리에서 발생했던 의도치않은 상태 변경을 방지한다.

**Comment by samseburn** [comment]
API 상태 관리를 위해 책에서는 상태 관리 라이브러리에서 호출하는 방법과 훅으로 호출하는 방법을 소개하고 있습니다. 
####  상태 관리 라이브러리에서 호출하기
서비스 코드를 사용해서 비동기 상태를 변화시킬 수 있는 함수를 제공하는 방식으로, 스토어를 사용하여 상태를 구독하는 형태로 관리합니다. 
전역 상태 관리자가 모든 비동기 상태에 접근하고 변경할 수 있기 때문에 쓸데없는 비동기 통신이 발생하거나 의도치 않은 상태 변경이 발생할 수 있습니다. 

#### 훅으로 호출하기
react-query나 useSwr 같은 훅을 사용하는 방법으로 사용법이 비교적 간단합니다. 
캐시를 사용하여 비동기 함수를 호출하며, 상태 관리 라이브러리에서 발생하는 의도치 않은 상태 변경을 방지하는 데 도움이 됩니다.
