### ISSUE TITLE
타입스크립트는 정적 언어인가요? 동적 언어인가요?

### ISSUE THREAD

**Issue by limejin** [deep-dive-everything/typescript-with-react#3]
📚 36p - 37p
📌 타입스크립트는 정적 언어인가요? 동적 언어인가요? 이유와 함께 답해주세요.

**Comment by hotdog1004** [comment]
### 타입스크립트는 `정적 타입`의 언어입니다.
타입은 타입을 결정하는 시점에 따라 `정적 타입`과 `동적 타입`으로 분류할 수 있습니다.
`정적 타입`의 경우 모든 변수의 타입이 **컴파일타임**에 결정되며, 코드 수준에서 개발자가 타입을 명시해줘야합니다. 
반면 `동적 타입`의 경우 변수 타입이 **런타임**에 결정됩니다.

**Comment by kwonhygge** [comment]
타입스크립트는 컴파일 시점에 타입이 결정되는 정적 타입 언어입니다

**Comment by limejin** [comment]
정적 언어이다. 동적/정적 언어의 구분은 타입 결정 시점에 따라 달라진다. 타입 스크립트는 컴파일 시점에 타입이 결정되므로 정적 언어이다.

**Comment by devsomda** [comment]
타입스크립트는 정적언어입니다. 동적언어와 달리 컴파일 시점에 타입이 결정되어 디버깅이 더 원활합니다.
