### ISSUE TITLE
훅을 사용해 비동기 함수를 호출 할 때, 컴포넌트가 최신 상태를 표현하는 방법으로는 무엇이 있나요?

### ISSUE THREAD

**Issue by devsomda** [deep-dive-everything/typescript-with-react#30]
📚 223p
📌 훅(react-query나 useSwr 등)을 사용해 비동기 함수를 호출 할 때,
컴포넌트가 최신 상태를 표현하는 방법으로는 무엇이 있나요?

**Comment by kwonhygge** [comment]
폴링이나 웹소켓을 사용하여 최신 상태의 데이터를 가져올 수 있습니다. 
폴링: 클라이언트가 주기적으로 서버에 요청을 보내 데이터를 업데이트 하는 것
웹소켓: 클라이언트와 서버간에 지속적인 양방향 통신 채널을 생성하여 실시간으로 데이터를 주고받는 방식

**Comment by hotdog1004** [comment]
이 경우 폴링이나 웹소켓 등의 방법을 사용할 수 있습니다.
폴링은 클라이언트가 주기적으로 서버에 요청을 보내 데이터를 업데이트 하는 것을 뜻합니다. 
웹소켓은 클라이어언트와 서버 사이에 양방향, 실시간 통신을 가능하게 하는 프로토콜입니다. 연결을 계속 유지하며 지속적으로 데이터를 주고 받을 수 있습니다.

**Comment by devsomda** [comment]
폴링 혹은 웹소켓을 통해 최신 상태를 표현할 수 있다.
폴링: 클라이언트가 주기적으로 요청을 보내 데이터를 업데이트 하는 것
웹소켓: 클라이언트와 서버가 양방향 통신을 통해 데이터를 지속적으로 주고받는 것

**Comment by limejin** [comment]
주기적으로 서버 정보를 가져오는 폴링이나 웹소캣 방법을 사용하면 최신 상태를 표현하는 것이 가능하다.

**Comment by samseburn** [comment]
폴링(polling)이나 웹소켓(websocket) 등의 방법을 사용하여 컴포넌트의 최신 상태를 표현할 수 있습니다. 
- 폴링: 클라이언트가 일정 간격으로 서버에 요청을 보내 최신 데이터를 가져오는 방식
- 웹소켓: 클라이언트와 서버 간의 양방향 통신 채널을 열어 데이터를 실시간으로 주고받을 수 있는 방식
