### ISSUE TITLE
프론트엔드 개발에서 API 모킹을 활용하는 이유와 그 이점에 대해 설명해주세요.

### ISSUE THREAD

**Issue by samseburn** [deep-dive-everything/typescript-with-react#31]
📚 239p - 248p
📌 

프론트엔드 개발에서 API 모킹을 활용하는 이유와 그 이점에 대해 설명해주세요. 
추가로 API 모킹을 위해 사용할 수 있는 방식이 있다면 어떤 게 있을지 알려주세요.

**Comment by kwonhygge** [comment]
프론트엔드 개발에서 API 모킹을 활용하면 서버 개발이 완료되지 않은 상태에서도 프론트엔드 구현을 해볼 수 있다는 장점이 있습니다. 또한 서버 상태에 문제가 발생했을 때에도 영향을 받지 않고 프론트엔드 개발을 할 수 있게 됩니다.
단순히 json 파일을 만들고 불러오는 방법이 있고 요청경로를 바꿔야하는 것이 부담된다면 NextApiHandle, axios-mock-adpater 같은 라이브러리를 사용하는 방법도 있습니다.

**Comment by hotdog1004** [comment]
API 모킹을 활용하면 서버 API가 완성 되지 않더라도 프론트엔드 개발을 진행할 수 있습니다. 만약 서버 상태에 문제가 생기더라도 영향을 받지 않고 프론트엔드 개발을 진행할 수 있다는 이점을 가집니다.
간단한 조회의 경우 json 파일을 만들어서 사용할 수 있고, axios-mock-adapter, NextApiHandler 등의 라이브러리를 활용하는 방법도 있습니다.

**Comment by devsomda** [comment]
서버 API 완성 전 프론트엔드 개발이 가능해 빠른 개발을 진행할 수 있다.
json파일을 만들어 사용하는 방법과 axios-mock-adapter, NextApiHandler 등 mock API 관련 라이브러리를 활용하는 방법이 있다.

**Comment by limejin** [comment]
서버 API 완성되기 전, 서버 상태가 불안정할 때, 프론트엔드 개발에 대한 테스트를 할 수 있다. 
JSON 파일을 활용하여 임의 응답으로 원하는 값을 반환할 수도 있고, 라이브러리를 활용하여 실제 서버에 요청을 보내는 것처럼 활용할 수 있다.
