### ISSUE TITLE
API 응답의 타입 오류

### ISSUE THREAD

**Issue by limejin** [deep-dive-everything/typescript-with-react#32]
📚 213p
📌 API 응답 타입 오류는 언제 발생하나요? 이 오류를 다루기 위해 어떻게 해야하나요? 타입 스크립트는 왜 이 오류를 해결하지 찾아내지 못하는지 설명해주세요.

**Comment by kwonhygge** [comment]
API 응답 타입 오류는 런타임에서 발생하므로 컴파일 타임에 타입을 검증하는 타입스크립트는 이를 발견할 수 없습니다.
이를 방지하려면 superstruct 같은 라이브러리를 사용할 수 있는데요. superstruct는 자바스크립트 데이터의 유효성 검사를 위한 라이브러리로 아래와 같이 사용 가능합니다.

```
import {
  assert,
  is,
  validate,
  object,
  number,
  string,
  array,
} from "superstruct";

const Article = object({
  id: number(),
  title: string(),
  tags: array(string()),
  author: object({
    id: number(),
  }),
});

const data = {
  id: 34,
  title: "Hello World",
  tags: ["news", "features"],
  author: {
    id: 1,
  },
};

assert(data, Article);
is(data, Article);
validate(data, Article);
```

**Comment by hotdog1004** [comment]
API 응답의 타입 오류는 런타임에 발생하기 때문에 타입스크립트는 이를 캐치할 수 없습니다. 
런타임 응답 타입 검증을 위해  Superstruct 등의 라이브러리를 사용할 수 있습니다.
Superstruct 라이브러리를 사용하면 컴파일 단계가 아닌 런타임에서도 적절한 데이터인지 확인하는 검사를 실행할 수 있습니다.

**Comment by devsomda** [comment]
API 응답 오류는 런타임에 발생하고,TypeScript는 컴파일 단계에서 타입을 검사하지만, 런타임 오류는 확인하지 못해 API 응답 타입 오류를 찾아낼 수 없다. 런타임에서 타입을 검증하기 위해 Superstruct 등의 라이브러리를 활용할 수 있다.

**Comment by limejin** [comment]
API 응답 타입 오류는 런타임에 발생하는데 타입 스크립트는 컴파일 타임 단계에서 타입을 검사하는 언어이기에 런타임에 발생하는 오류를 잡기 어렵습니다. 이러한 점을 보완하기 위해서는 런타임 응답 타입 검증을 지원하는 라이브러리를 사용하면 됩니다.

**Comment by samseburn** [comment]
타입스크립트는 정적 검사 도구이기 때문에 런타임에서 발생하는 오류를 찾아낼 수 없습니다. 따라서, 런타임에 발생할 수 있는 API 응답 타입 오류를 방지하려면 superstruct나 zod와 같은 유효성 검사 라이브러리를 사용하는 것이 좋습니다.
