### ISSUE TITLE
Fetch로 API를 요청하는 방법과 서비스 레이어로 분리하는 방법의 장점과 단점을 설명해주세요.

### ISSUE THREAD

**Issue by frogk** [deep-dive-everything/typescript-with-react#33]
📚 200p - 201p
📌 Fetch로 API를 요청하는 방법과 서비스 레이어로 분리하는 방법의 장점과 단점을 설명해주세요.

**Comment by devsomda** [comment]
Fetch
장점: 간편하게 구현이 가능하다.
단점: 같은 코드의 중복이 발생할 수 있다. 변경 등 유지보수 면에서 취약하다.

서비스 레이어로 분리한 경우
장점: 코드 중복을 줄일 수 있다.
단점: fetch 함수를 서비스 레이어로 이동하는 것만으로는 API 요청 정책 변경 등에서 자유로울 수 없다. (이를 해결하기 위해 axios 라이브러리를 활용할 수 있다)

**Comment by limejin** [comment]
fetch 를 활용하는 것은 자바스크립트 내장 기능이기 때문에 별도의 설치가 불필요합니다. 그러나 API 수정 시, 코드 수정이 번거롭다는 단점이 있습니다. 이를 서비스 레이어로 분리하면 재사용성, 유지보수성, 일관성을 향상시켜 코드 수정 범위가 줄어듭니다. 그러나 이 방법도 API 변경 시, 코드 수정의 번거로움에 대한 문제가 완전히 해결되는 것은 아닙니다. Axios를 사용하면 API 관리가 간편해집니다.

**Comment by samseburn** [comment]
#### `fetch()`
- 장점: 자바스크립트의 내장 함수로 별도의 라이브러리 의존성 없이 간단히 구현할 수 있습니다.
- 단점: 개발자가 API 요구 사항에 맞춰 직접 설정을 해야 하므로, 에러 핸들링과 유지 보수가 까다로울 수 있습니다.
#### 서비스 레이어로 분리하기
- 장점: API 요청 로직을 중앙에서 관리하여, 여러 컴포넌트에서 동일한 요청 로직을 재사용할 수 있습니다. API가 변경될 경우 서비스 레이어에서만 수정하면 되므로 유지 보수에도 용이합니다.
- 단점: 서비스 레이어를 위한 초기 세팅이 필요하며, 팀 차원에서 서비스 구조와 사용법을 학습해야 합니다. 또한, Axios 같은 라이브러리에 비해 커스텀 헤더 추가나 토큰 관리 등 다양한 API 정책을 처리하는 것이 더 까다로울 수 있습니다.
