### ISSUE TITLE
함수 컴포넌트에서 ref를 다룰때 주의해야할점이 무엇일까요?

### ISSUE THREAD

**Issue by kwonhygge** [deep-dive-everything/typescript-with-react#34]
📚 263p - 267p
📌 함수 컴포넌트에서 ref를 다룰때 주의해야할점이 무엇일까요? (왜 forwardRef를 사용해야하는지 이유)

**Comment by hotdog1004** [comment]
클래스 컴포넌트에서 ref 객체는 마운트된 컴포넌트의 인스턴스를 current 속성 값으로 가집니다.
하지만 함수 컴포넌트에서는 생성된 인스턴스가 없기 때문에 ref에 기대한 값이 할당되지 않으므로 이를 주의해야합니다.

예시 코드
```tsx
// 함수 컴포넌트로 만들어진 Button 컴포넌트를 사용할 때
// 전달받은 ref가 Button 컴포넌트의 button 태그를 바라보지 않음
const WrappedButton = () => {
  const buttonRef = useRef();

  return (
    <div>
        <Button ref={buttonRef}/>
    </div>
  );
};

```
React.forwardRef 메서드를 사용하면 함수컴포넌트에서도 ref를 전달 받을 수 있도록 처리할 수 있습니다.

예시 코드
```tsx
// forwardRef를 사용해 ref를 전달받을 수 있도록 구현
const Button = forwardRef((props, ref)=>{
   return <button ref={ref} {...props}>버튼</button>;
});

// buttonRef가 Button 컴포넌트의 button 태그를 바라볼 수 있음 
const WrappedButton = () => {
  const buttonRef = useRef();

  return (
    <div>
        <Button ref={buttonRef}/>
    </div>
  );
};

```

**Comment by kwonhygge** [comment]
```jsx
const ExampleComponent = ({ref}) => <div ref={ref}></div>

function App(){
const ref = useRef(null)

return <ExampleComponent ref={ref} />
}
```

함수 컴포넌트는 위와 같이 우리가 일반적으로 사용하는 방식으로 정의된 컴포넌트에 ref를 전달하면 원하는 값을 읽어올 수 없습니다.
그 이유는 함수 컴포넌트가 인스턴스를 가지지 않기 때문입니다. ref는 React 컴포넌트의 인스턴스에 접근하기 위해 사용됩니다. 
그러나 함수 컴포넌트는 인스턴스를 가지지 않고 함수로 호출되기 때문에 React는 ref를 어디에 연결해야하는지 알 수 없습니다.
이를 해결하기 위해 forwardRef라는 기능을 사용해 부모 컴포넌트에서 전달한 ref를 함수 컴포넌트의 원하는 요소에 연결할 수 있습니다.

**Comment by samseburn** [comment]
```tsx
// ❌ 동작하지 않음
const Input = ({ ref }) => {
  return <input ref={ref} />
}
```
함수 컴포넌트에서 ref를 다룰 때 다음과 같은 제약사항이 있습니다.
- 함수 컴포넌트는 인스턴스를 생성하지 않기 때문에 기본적으로 ref를 전달받을 수 없음
- props로 ref를 직접 전달 받더라도 undefined 할당

이와 같이 동작하는 이유는 함수 클래스와 클래스 컴포넌트의 차이점에서 발생합니다.
- 클래스 컴포넌트: ref 객체의 current는 마운트된 컴포넌트 인스턴스를 가리킴
- 함수 컴포넌트: 생성된 인스턴스가 없어 ref 참조 어려움

다만, 이런 제약을 극복하기 위해 함수 컴포넌트에서도 `forwardRef`를 사용하여 ref를 전달받을 수 있습니다. 
```tsx
const Input = forwardRef<HTMLInputElement, Props>(({ ref }) => {
  return <input ref={ref} />
})
```
`forwardRef`를 이용하면 아래와 같이 부모 컴포넌트에서 ref를 전달 가능합니다.
```tsx
const WrappedInput = () => {
  const inputRef = useRef<HTMLInputElement>(null)

  useEffect(() => {
    inputRef.current?.focus()
  }, [])

  return <Input ref={inputRef} />
}
```

**Comment by devsomda** [comment]
함수 컴포넌트에서 ref를 props로 전달하여 할당하더라도, ref가 바로 그곳을 바라보지 않는다. 함수 컴포넌트에서는 생성된 인스턴스가 없기 때문에 ref에 기대한 값이 할당되지 않는 것이다. 이 제약을 극복하기 위해 forwardRef를 사용한다.

**Comment by limejin** [comment]
함수 컴포넌트에서는 생성된 인스턴스가 없기 때문에 ref에 기대한 값이 할당되지 않는다. 이러한 제약을 도와주는 것이 forwardRef 메서드이다.
