### ISSUE TITLE
React.ReactElement, JSX.Element, React.ReactNode 타입에 대해 설명해주세요.

### ISSUE THREAD

**Issue by hotdog1004** [deep-dive-everything/typescript-with-react#35]
📚 253p - 254p
📌 React.ReactElement, JSX.Element, React.ReactNode 타입에 대해 설명해주세요.(포함 관계까지 함께 설명)

**Comment by hotdog1004** [comment]
render 메서드와 함수 컴포넌트의 반환 타입에는  React.ReactElement, JSX.Element, React.ReactNode 타입이 있습니다.

### React.ReactElement
- 함수 컴포넌트의 반환 타입인 ReactElement는 아래와 같이 정의됩니다.
  ```tsx
  interface ReactElement<P = any,
    T extends string | JSXElementConstructor<any> = 
    | string 
    | JSXElementConstructor<any>
  > {
    type: T;
    props: P;
    key: string | null;
  }
  ```
- React.ReactElement를 호출하는 형태의 구문으로 변환하면 반환 타입은 ReactElement가 됩니다.
- 리액트 가상 DOM의 엘리먼트는 ReactElement 형태로 저장되며 ReactElement 타입은 리액트 컴포넌트를 객체 형태로 저장하기 위한 포맷이라고 할 수 있습니다.

### JSX.Element
```tsx
declare global {
  namespace JSX {
    interface Element extends React.ReactElement<any, any> {}
  }
}
```
- JSX.Element 타입은 React.ReactElement를 확장하고 있는 타입입니다.
- 글로벌 네임스페이스에 정의되어 있어 외부 라이브러리에서 컴포넌트 타입을 재정의 할 수 있는 유연성을 제공합니다. 
  위와 같은 이유로 컴포넌트 타입을 재정의하거나 변경하는 것이 용이하다는 특성을 가집니다.
### React.ReactNode
```tsx
  type ReactNode =
    | ReactElement
    | string
    | number
    | Iterable<ReactNode>
    | ReactPortal
    | boolean
    | null
    | undefined
    | DO_NOT_USE_OR_YOU_WILL_BE_FIRED_EXPERIMENTAL_REACT_NODES[
      keyof DO_NOT_USE_OR_YOU_WILL_BE_FIRED_EXPERIMENTAL_REACT_NODES
    ];
```
- ReactElement 외 string, number, boolean 등 여러 타입을 포함합니다.

### 포함관계 
- JSX.Element ⊂ ReactElement ⊂ ReactNode

**Comment by kwonhygge** [comment]
React.ReactElement는 React.createElement를 호출하여 생성된 react element의 타입을 말합니다. 
JSX.Element는 React.ReactElement를 확장한 타입으로 외부 라이브러리에서 컴포넌트 타입을 재정의할 수 있는 유연성을 제공합니다.
React.ReactNode는 React.ReactElement와 string, boolean 등 여러 타입을 포함한 타입입니다.

셋의 포함관계를 정리하면 아래와 같습니다.
JSX.Element ⊂ ReactElement ⊂ ReactNode

**Comment by samseburn** [comment]
#### `ReactElement`
- JSX가 `createElement`메서드 호출로 생성된 리액트 엘리먼트를 나타내는 타입
```tsx
interface ReactElement<
  P = any,
  T extends string | JSXElementConstructor<any> = string | JSXElementConstructor<any>,
> {
  type: T
  props: P
  key: string | null
}
```
#### `JSX.Element`
- `ReactElement`를 확장하고 있는 타입이며, 제네릭으로 props와 타입 필드에 대해 any 타입을 가지도록 확장
- 글로벌 네임스페이스에 정의하여 외부 라이브러리에서 컴포넌트 타입을 재정의 할 수 있는 유연성 제공
```tsx
declare global {
	namespace: JSX {
		interface Element extends React.ReactElement<any, any> {}
	}
}
```

#### `ReactNode`
- 리액트에서 사용할 수 있는 모든 요소의 타입
```tsx
type ReactText = string | number
type ReactChild = ReactElement | ReactText
type ReactFragment = {} | Iterable<ReactNode>

type ReactNode = ReactChild | ReactFragment | ReactPortal | boolean | null | undefined
```

#### 포함 관계
![image](https://github.com/user-attachments/assets/68b3a4bf-6e60-4ba5-a2fc-217ef2d42d9c)

**Comment by devsomda** [comment]
JSX.Element: JSX를 통해 생성된 요소의 타입으로, React 컴포넌트가 반환할 수 있는 가장 기본적인 요소.
React.ReactElement: JSX.Element와 유사하지만, 더 넓은 범위를 포함하며 React에서 생성된 모든 요소를 포괄.
React.ReactNode: 가장 넓은 타입으로, 문자열, 숫자, ReactElement, null, undefined, boolean 등을 모두 포함하여 React 컴포넌트가 렌더링할 수 있는 모든 타입을 표현.

포함 관계: JSX.Element ⊆ React.ReactElement ⊆ React.ReactNode

**Comment by limejin** [comment]
React.ReactElement : 함수 컴포넌트 반환 타입, 리액트 컴포넌트를 객체 형태로 저장하기 위한 포맷
JSX.Element : ReactElement를 확장하고 있는 타입, 글로벌 네임스페이스에 정의되어있어 외부 라이브러리에서 컴포넌트 타입을 재정의하는 유연성 제공
React.ReactNode : ReactElement 외에도 boolean, string, number 등의 여러 타입 포함

포함 관계 : ReactNode ⊃ ReactElement ⊃ JSX.Element (JSX.Element가 ReactElement를 확장하면서도 더 좁은 범위를 가지는 이유는, JSX가 ReactElement의 특정 서브셋(JSX 문법으로 작성된 React 요소)만 표현하기 때문)
