### ISSUE TITLE
`ComponentPropsWithoutRef`와 `DetailedHTMLProps`의 차이점은 무엇인가요? 

### ISSUE THREAD

**Issue by samseburn** [deep-dive-everything/typescript-with-react#37]
📚 261 - 267p
📌 `ComponentPropsWithoutRef`와 `DetailedHTMLProps`의 차이점은 무엇인가요? 또한, 특정 상황에서 `ComponentPropsWithoutRef`를 사용하는 것이 적합한 경우는 언제인가요?

**Comment by hotdog1004** [comment]
HTML 태그의 속성 타입을 활용하는 대표적인 방법으로 리액트의 **ComponentPropsWithoutRef**와 **DetailedHTMLProps** 타입을 활용하는 방법이 있습니다.
두 타입은 함수 컴포넌트의 props에 타입을 가져올 때 **ref 속성의 포함 여부**에 대한 차이를 가집니다.
DetailedHTMLProps는 ref 속성을 포함하는 타입이지만, 실제로는 동작하지 않는 ref를 받도록 타입이 지정되어 예기치 않은 에러가 발생할 수 있습니다.
ComponentPropsWithoutRef는 ref 속성을 포함하지 않습니다.
하지만 React.forwardRef 메서드를 사용하여 ref를 전달 받을 수 있으며, DetailedHTMLProps보다 안전하게 사용할 수 있습니다.
따라서 HTML 속성을 확장하는 props를 설계할 때는 ComponentPropsWithoutRef 타입을 사용해서 ref가 실제로 forwardRef와 함께 사용될 때만 props로 전달되도록 타입을 정의하는 것이 안전합니다.

**Comment by kwonhygge** [comment]
ComponentPropsWithoutRef와 DetailedHTMLProps는 ref 속성 포함여부에 따른 차이가 있습니다. 
함수 컴포넌트에서는 ref를 전달받더라도 ref를 연결할 인스턴스가 없기 때문에 ref에 기대한 값이 할당되지 않습니다.
따라서 HTML 속성을 확장하는 props를 설계할 때는 ComponentPropsWithoutRef를 사용해서 ref가 실제로 forwardRef와 함께 사용될때만 props로 전달되어 사용되도록 타입을 정의하는 것이 안전합니다.

**Comment by devsomda** [comment]
DetailedHTMLProps: HTML 요소의 모든 속성을 포함하여, DOM 요소에 직접 적용 가능한 세부 HTML 속성들을 제공. 
ComponentPropsWithoutRef: 특정 React 컴포넌트의 모든 props 타입을 가져오되, ref 속성은 제외. 주로 커스텀 컴포넌트를 만들 때, ref가 필요 없는 경우에 사용하기 적합

**Comment by limejin** [comment]
ComponentPropsWithoutRef는 ref를 포함하지 않고 DetailedHTMLProps는 ref를 포함합니다.

ComponentPropsWithoutRef를 사용하는 것이 적합한 경우 : HTML 속성을 확장하는 props를 설계할 때 (특정 HTML 요소에 추가적인 props를 더하면서도, 기존 HTML 속성을 모두 지원하고 싶을 때)
