### ISSUE TITLE
useEffect 내에 비동기 함수가 들어갈 수 없는 이유가 무엇일까요?

### ISSUE THREAD

**Issue by kwonhygge** [deep-dive-everything/typescript-with-react#39]
📚 290p
📌 useEffect 내에 비동기 함수가 들어갈 수 없는 이유가 무엇일까요?

**Comment by hotdog1004** [comment]
useEffect의 타입 정의(@types/react v18 기준)
```ts
  type DependencyList = readonly unknown[];
  type EffectCallback = () => void | Destructor;
  function useEffect(effect: EffectCallback, deps?: DependencyList): void;
```
useEffect의 첫번째 인자인 effect의 타입인 EffectCallback은 Destructor를 반환하거나 아무것도 반환하지 않는 함수입니다. 
여기에 Promise 타입은 없으므로 useEffect의 콜백함수에는 비동기 함수가 들어갈 수 없습니다
또한, 만약 useEffect에서 비동기 함수를 호출할 수 있다면 경쟁상태를 불러일으킬 수 있고 이로 인해 여러 문제가 발생할 수 있습니다. 
이와 같은 이유로 비동기 함수는 useEffect 내에 들어갈 수 없습니다.

**Comment by kwonhygge** [comment]
useEffect의 콜백은 Promise를 반환하지 않는 함수입니다. 따라서 비동기함수가 들어갈 수 없습니다.
그 이유는 비동기함수의 응답이 오고있는 중에 dependency가 변경되면 원하지 않는 동작을 초래할 수 있기 때문입니다.
아래 코드에서 fetch의 응답이 오기 전에 dependency가 변경되어 두번째 useEffect가 호출되는 경우가 있습니다. 
만일 이때 두번째 fetch의 응답이 먼저 도착한다면 state는 두번째 응답으로 업데이트 됩니다. 이후 첫번째 fetch의 응답이 도착하게 된다면 최신 데이터가 아닌 이전의 데이터가 업데이트 될 수 있습니다.
```js
useEffect(() => {
  const fetchData = async () => {
    const response = await fetch("https://example.com/api/data");
    const data = await response.json();
    setState(data); // 상태 업데이트
  };
  
  fetchData();
}, [dependency]);
```

**Comment by samseburn** [comment]
`useEffect` 내에 비동기 함수가 들어갈 수 없는 이유를 설명하려면 먼저 `useEffect`의 타입 정의를 먼저 확인해야 합니다.

```tsx
function useEffect(effect: EffectCallback, deps?: DependencyList): void
type DependencyList = readonly unknown[]
type EffectCallback = () => void | Destructor
```
`useEffect`의 첫 번째 인자로 넘겨주는 `effect`의 타입은 `Destructor`를 반환하거나 아무것도 반환하지 않는 함수입니다. 비동기 함수는 항상 `Promise`를 반환합니다. 따라서 async를 사용하면 `Promise`가 반환되는데, 이는 `effect`에 사용할 수 없는 값입니다.

즉, 경쟁 상태를 방지하고자 `useEffect` 내에 비동기 함수가 들어갈 수 없게 설계되었습니다. 
`useEffect` 내부에서 비동기 작업을 처리하면 렌더링과 상태 업데이트 간의 순서와 일관성이 깨질 수 있습니다. 특히, 비동기 작업이 완료되기 전에 컴포넌트가 언마운트되거나 의존성이 변경되면, 불필요한 작업이 실행되거나 상태가 잘못 업데이트될 수 있습니다.

**Comment by limejin** [comment]
useEffect 타입 정의를 보면 첫번째 인자 타입이 Destructor를 반환하거나 아무것도 반환하지 않는(void) 함수입니다. 이와 같이 설계된 이유는 경쟁 상태(여러 프로세스가 공유 자원에 동시에 접근하여 실행순서나 타이밍을 예측할 수 없게 되는 현상)를 발생시키지 않기 위해서 입니다.

**Comment by devsomda** [comment]
useEffect의 첫번째 인자인 EffectCallback은 Promise 타입을 반환하지 않기 때문이다
