### ISSUE TITLE
덕타이핑과 구조적 타이핑의 공통점과 차이점

### ISSUE THREAD

**Issue by frogk** [deep-dive-everything/typescript-with-react#4]
📚 46p - 48p
📌 자바스크립트의 덕타이핑과 타입스크립트의 구조적타이핑의 공통점과 차이점을 설명해주세요.

**Comment by hotdog1004** [comment]
### 공통점
- 두 방식 모두 구조적 특징을 기반으로 하는 타이핑 방식입니다.
→ 타입의 이름이 다르더라도 객체가 가지고 있는 프로퍼티가 동일하다면 호환이 가능합니다.

### 차이점
- 타입을 검사하는 시점에 차이가 있습니다.
→ `구조적 타이핑`은 컴파일 시점에 타입이 체크되지만, `덕 타이핑`은 런타임 시점에 타입이 체크됩니다.

**Comment by kwonhygge** [comment]
덕 타이핑과 구조적 타이핑은 모두 타입의 구조가 같다면 타입 호환이 가능하다는 특성을 가지고 있습니다. 
둘은 타입검사 기점에서 차이가 있는데요. 덕 타이핑은 런타임 시점에 타입을 검사하지만 구조적 타이핑은 컴파일 시점에 타입을 검사합니다

**Comment by limejin** [comment]
덕 타이핑 : 어떤 함수의 매개변숫값이 올바르게 주어진다면 그 값이 어떻게 만들어졌는지 신경쓰지 않고 사용
구조적 타이핑 : 명시적인 이름 기반으로 타입을 구분하지 않고 객체, 함수가 가진 구조적 특징에 기반하여 타이핑하는 방식
타입스크립트는 자바스크립트의 덕 타이핑 특징을 수용하여 구조적 타이핑 방식을 채택했다. 이를 통해 유연한 타이핑이 가능해졌다.

공통점 : 객체가 가진 속성 기반 타입 검사
차이점 : 타입 검사 시점 (덕타이핑 : 런타입 / 구조적 타이핑 : 컴파일 시점)

**Comment by devsomda** [comment]
차이점
자바스크립트는 런타임에서 객체의 속성과 메서드만을 확인하며, 타입에 대한 정의는 존재하지 않습니다.
타입스크립트는 컴파일 시점에 객체의 구조를 확인하여 타입 체크를 수행하며, 더 엄격한 타입 검사와 오류를 사전에 방지할 수 있습니다.
