### ISSUE TITLE
useRef를 props로 넘겨줄 수 없는 이유는 무엇인가요?

### ISSUE THREAD

**Issue by devsomda** [deep-dive-everything/typescript-with-react#40]
📚 295p - 296p
📌useRef를 props로 넘겨줄 수 없는 이유는 무엇인가요? / 그럼 ref는 어떤 방식으로 전달해야 하나요?

**Comment by hotdog1004** [comment]
`ref`라는 속성의 이름은 리액트에서 DOM 요소 접근이라는 특수한 목적으로 사용되므로 props를 넘겨주는 방식으로 전달할 수 없습니다. 만약 `ref`라는 이름으로 props를 넘겨주고 싶다면 `forwardRef`를 사용해야합니다.

**예시코드**
```tsx
  // forwardRef를 사용한 코드
  interface Props {
    name: string;
  }
  
  const MyInput = forwardRef<HTMLInputElement, Props>((props, ref) => {
    return (
      <div>
        <label>{props.name}</label>
        <input ref= {ref} />
      </div>
    );
  });
```
위처럼 forwardRef의 두 번째 인자에 ref를 넣어 자식컴포넌트로 ref를 전달할 수 있습니다.

**Comment by kwonhygge** [comment]
ref 속성은 리액트에서 DOM 요소 접근이라는 특수한 목적으로 사용되므로 props를 넘겨주는 방식으로 전달할 수 없습니다.
따라서 forwardRef를 사용하여 전달해주어야 합니다.

**Comment by samseburn** [comment]
ref라는 속성의 이름은 리액트에서 'DOM 요소 접근'이라는 특수한 목적으로 사용되기 때문에 props를 넘겨주는 방식으로 전달할 수 없습니다. 
따라서 리액트 컴포넌트에서 ref를 prop으로 전달하기 위해서는 `forwardRef`를 사용해야 합니다. 

```tsx

type InputProps = {
  name: string
}

const Input = forwardRef<HTMLInputElement, InputProps>((props, ref) = {
  return (
    <div>
      <label>{props.name}</label>
      <input ref={ref} {...props} />
    </div>
  )
})


const ParentInput = () => {
  const inputRef = useRef<HTMLInputElement>(null)

  return <Input ref={inputRef} />
}


```

**Comment by limejin** [comment]
ref라는 속성의 이름은 리액트에서 DOM 요소 접근이라는 특수 목적으로 사용되기 때문에 props를 넘겨주는 방식으로 전달될 수 없습니다. ref를 prop으로 전달하고 싶다면 forwardRef를 사용하면 됩니다.

**Comment by devsomda** [comment]
ref 속성은 DOM 요소 접근이라는 목적으로 사용되기 때문이다. 전달을 위해서는 forwardRef를 사용해야 한다.
