### ISSUE TITLE
리액트 훅을 안전하게 사용하기 위해 지켜야 하는 두 가지 규칙

### ISSUE THREAD

**Issue by hotdog1004** [deep-dive-everything/typescript-with-react#41]
📚 300p - 301p
📌 리액트 훅을 안전하게 사용하기 위해 지켜야 하는 두 가지 규칙에 대해 설명해주세요.

**Comment by hotdog1004** [comment]
1. 훅은 항상 최상위 레벨에서 호출되어야 합니다. 
   조건문, 반복문, 중첩 함수 등의 내부에서는 훅을 호출하지 않아야 합니다. 
2. 훅은 항상 함수 컴포넌트나 커스텀 훅 등의 리액트 컴포넌트 내에서만 호출되어야 합니다.

리액트에서 훅은 호출 순서에 의존합니다. 
모든 컴포넌트 렌더링에서 훅의 순서가 항상 동이랗게 유지되어야 하며, 이를 통해 항상 동일한 컴포넌트 렌더링이 보장됩니다.
따라서 위 규칙들을 지키며 훅을 사용하는 것이 중요합니다.

**Comment by kwonhygge** [comment]
훅은 항상 최상위 레벨에서 호출되어야 합니다. 조건문, 반복문, 중첩 함수, 클래스 등의 내부에서는 훅을 호출하지 않아야 합니다.
그리고 항상 함수컴포넌트나 커스텀 훅 등의 리액트 컴포넌트 내에서만 호출되어야 합니다.

**Comment by samseburn** [comment]
리액트 훅을 안전하게 사용하기 위해서는 다음 2가지 규칙을 지켜야 합니다. 해당 규칙들을 지키면 컴포넌트의 모든 상태 관련 로직을 좀 더 명확하게 드러낼 수 있습니다.

- 훅을 항상 최상위 레벨에서 호출되어야 합니다. 
- 훅은 항상 함수 컴포넌트나 커스텀 훅 등의 리액트 컴포넌트 내에서만 호출되어야 합니다.

리액트에서 훅은 호출 순서에 의존하기 때문에 모든 컴포넌트 렌더링에서 훅의 순서가 항상 동일하게 유지되어야 하며, 이를 통해 항상 동일한 컴포넌트 렌더링이 보장됩니다.

**Comment by limejin** [comment]
최상단 레벨에서 호출할 것, 함수컴포넌트/커스텀 훅 등 리액트 컴포넌트 내에서만 호출할 것입니다. 이는 리액트의 렌더링 순서를 지키기 위함입니다. 리액트는 훅의 호출 순서에 의존하여 컴포넌트 상태와 사이트 이펙트를 관리하기 때문에 훅이 예측가능하도록 동작하는 것이 중요합니다.

**Comment by devsomda** [comment]
1. 훅은 최상위 레벨에서 호출된다.
2. 훅은 항상 함수 컴포넌트나 커스텀 훅 등 리액트 컴포넌트 안에서만 호출된다.
