### ISSUE TITLE
코드를 useLayoutEffect 훅으로 변경해주세요.

### ISSUE THREAD

**Issue by limejin** [deep-dive-everything/typescript-with-react#42]
📚 292p - 293p
📌 아래 코드를 useLayoutEffect 훅으로 변경해주세요. DOM 업데이트의 순서가 어떻게 변경되며, 이러한 변화가 사용자에게 보이는 화면에 어떤 영향을 미치는지 설명해주세요.
```
const [name, setName] = useState("");

useEffect(() => {
  // 매우 긴 시간이 흐른 뒤 아래의 setName()을 실행한다고 생각하자
  setName("배달이");
}, []);

return (
  <div>
    {안녕하세요, ${name}님!}
  </div>
);

```

**Comment by hotdog1004** [comment]
**useLayoutEffect 적용 코드**
```tsx
const [name, setName] = useState("");
  useLayoutEffect(() => {
    // 매우 긴 시간이 흐른 뒤 아래의 setName()을 실행한다고 생각하자
    setName("배달이");
  }, []);
  
  return (
    <div>
      {안녕하세요, ${name}님!}
    </div>
  );
```

DOM 업데이트 순서 관점에서 `useLayoutEffect`는 렌더링 후 페인팅 전에 실행됩니다. 

`useEffect`를 적용한 경우 사용자가 화면을 처음 보았을 때, **안녕하세요,   님!** 과 같이 빈 이름을 보게 되며, 시간이 지난 후 완성된 화면을 보게 됩니다.
하지만 `useLayoutEffect`를 적용한 경우 사용자는 처음부터 **안녕하세요, 배달이님!** 과 같이 완성된 화면을 보게 됩니다.

**Comment by kwonhygge** [comment]
위 코드에서 useEffect를 useLayoutEffect로 변경하게 되면 화면에 해당 컴포넌트가 그려지기 전에 콜백 함수를 실행하기 때문에 첫번째 렌더링때 {name}에 빈 값이 들어가있는것을 방지할 수 있습니다.
useEffect -> 안녕하세요, 님!
useLayoutEffect -> 안녕하세요, 배달이님!

**Comment by samseburn** [comment]
```tsx
const [name, setName] = useState("")

useLayoutEffect(() => {
  setName("배달이")
}, [])

return (
  <div>
    {안녕하세요, ${name}님!}
  </div>
)
```
`useLayoutEffect`는 DOM이 화면에 그려지기 전에 실행됩니다. 따라서 빈 문자열 화면이 보이지 않고 바로 **안녕하세요 배달이님!** 이라는 문구가 화면이 표시됩니다. 사용자가 깜빡임 없이 화면을 볼 수 있기 때문에 매끄러운 사용자 경험을 주지만 비용이 더 크기 때문에, 정말 필요한 경우에만 사용해야 합니다. 

일반적으로 사이드 이펙트를 처리할 때는 `useEffect`를 사용하고, 화면 렌더링 직전에 필수적인 작업이 필요할 때 `useLayoutEffect`를 사용하는 것을 권장합니다.

**Comment by devsomda** [comment]
import { useState, useLayoutEffect } from 'react';

const MyComponent = () => {
  const [name, setName] = useState("");

  useLayoutEffect(() => {
    // 매우 긴 시간이 흐른 뒤 아래의 setName()을 실행한다고 생각하자
    setName("배달이");
  }, []);

  return (
    <div>
      안녕하세요, {name}님!
    </div>
  );
};
브라우저가 DOM을 화면에 그리기 전에 상태 업데이트가 완료되므로, 사용자에게는 처음부터 안녕하세요, 배달이님!이 보인다.
