### ISSUE TITLE
다음 코드에서 발생하는 타입 오류를 수정하세요.

### ISSUE THREAD

**Issue by samseburn** [deep-dive-everything/typescript-with-react#43]
📚 294p - 297p
📌 다음 코드에서 발생하는 타입 오류를 수정하고 타입 오류가 발생하는 이유도 설명해주세요. 

```tsx
import { useRef } from 'react';

const MyComponent = () => {
  const inputRef = useRef<HTMLInputElement>(null);

  const focusInput = () => {
    inputRef.current.focus();  // 타입 오류 발생
  };

  return <input ref={inputRef} />;
};

```

**Comment by kwonhygge** [comment]
위 코드에서 타입 오류가 발생하는 이유는 useRef<HTMLInputElement>(null)로 초기값을 null로 설정했기 때문입니다. useRef의 current 속성은 null일 수도 있고, HTMLInputElement일 수도 있기 때문에 inputRef.current의 타입이 HTMLInputElement | null로 추론됩니다.

아래처럼 inputRef.current가 null이 아님을 보장하는 조건문을 추가하여 해결할 수 있습니다.

```ts
import { useRef } from 'react';

const MyComponent = () => {
  const inputRef = useRef<HTMLInputElement>(null);

  const focusInput = () => {
    if (inputRef.current) {
      inputRef.current.focus();
    }
  };

  return <input ref={inputRef} />;
};
```

**Comment by limejin** [comment]
```ts
import { useRef } from 'react';

const MyComponent = () => {
  const inputRef = useRef<HTMLInputElement>(null);

  const focusInput = () => {
    inputRef.current?.focus();  // 타입 오류 해결 =>  null일 때, focus를 호출할 수 없기 때문에 오류가 발생하는데 옵셔널 체이닝을 사용하여 null이 아닌 경우에만 focus 호출하도록 변경하여 해결
  };

  return <input ref={inputRef} />;
};

```

**Comment by devsomda** [comment]
타입 오류는 inputRef.current의 값이 null일 수 있기 때문이다. (useRef 훅으로 생성된 ref 객체의 current 속성은 초기값으로 null을 가지며, 실제 DOM 요소가 렌더링된 후에야 참조를 설정)

import { useRef } from 'react';

const MyComponent = () => {
  const inputRef = useRef<HTMLInputElement>(null);

  const focusInput = () => {
    if (inputRef.current) {
      inputRef.current.focus(); // null 체크 후 호출
    }
  };

  return <input ref={inputRef} />;
};
