### ISSUE TITLE
이 코드에서 발생할 수 있는 문제점과 해결 방법을 설명해주세요.

### ISSUE THREAD

**Issue by hotdog1004** [deep-dive-everything/typescript-with-react#44]
📚 312p - 313p
📌 아래의 코드에서는 아이템 목록이 변경될 때마다 선택된 아이템 목록을 가져오기 위해 useEffect로 동기화 작업을 하고 있습니다. 
이 코드에서 발생할 수 있는 문제점과  해결 방법을 설명해주세요. 
그리고 해결 방법을 토대로 코드를 개선해주세요. 
(문제점은 두 개 이상 작성)

```tsx
  // 아이템 목록과 선택된 아이템 목록을 가지고 있는 코드
  import {useState, useEffect} from 'react';
  
  const [items, setItems] = useState<Item[]>([]);
  const [selectedItems, setSelectedItems] = useState<Item[]>([]);
  
  useEffect(() => {
    setSelectedItems(items.filter((item) = > item.isSelected));
  }, [items]);
```

**Comment by kwonhygge** [comment]
이 코드에서 발생할 수 있는 문제점은 items가 selectedItems와 동기화되지 않을 수 있다는 것입니다. 또 selectedItems 안에 items에서 가져온 데이터가 아닌 데이터가 들어가는 것도 구조적으로 가능하기 때문에 오류가 발생할 가능성이 존재합니다.

단일 출처가 아닌 여러 출처를 가지게 된 것이 문제이므로 계산된 값을 새로운 변수에 담는 방식으로 문제를 해결할 수 있습니다. 이때 useMemo를 사용한다면 Items가 변경될 때만 계산을 수행하게 할 수 있습니다.

```tsx
const [items, setItems] = useState<Item[]>([]);
  const selectedItems = useMemo(
    () => items.filter((item) => item.isSelected),
    [items]
  );
```

**Comment by hotdog1004** [comment]
items와 selectedItems가 동기화되지 않을 수 있다는 것이 문제입니다. 또한 selectedItems를 사용해서 items에서 가져온 데이터가 아닌 임의의 데이터셋을 설정하는 것도 구조적으로 가능하기 때문에 오류가 발생할 가능성이 있습니다.
이처럼 새로운 상태를 정의함으로써 단일 출처가 아닌 여러 출처를 가지게 되었고, 이에 따라 동기화문제가 발생할 수 있습니다.

주어진 코드는 상태로 정의하지 않고 자바스크립트 변수로 담는 방식으로 개선할 수 있습니다.
```tsx
const [items, setItems] = useState<Item[]>([]);
const selectedItems = items.filter((items)=> item.isSelected);
```

**Comment by frogk** [comment]
1. items와 selectedItems가 동기화되지 않을 수 있습니다.
2. setSelectedItems를 사용하여 items에서 가져온 데이터가 아닌 임의의 데이터셋을 설정하는 것도 구조적으로 가능하기 때문에 오류가 발생할 가능성이 있습니다.

여러 출처를 하나의 출처로 합치는 방법을 고려해야합니다. 상태로 정의하지 않고 계산된 값을 자바스크립트 변수로 담는 방식으로 개선할 수 있습니다.

```tsx
const [items, setItems] = useState<Item[]>([]);
const selectedItems = items.filter((items)=> item.isSelected);

**Comment by devsomda** [comment]
문제 1: items와 selectedItems가 동기화되지 않을 가능성이 있다. setSelectedItems를 통해 items와 관계없는 임의의 데이터를 설정할 수도 있으므로, 데이터 불일치로 인한 오류가 발생할 수 있다

문제 2: 여러 상태를 하나의 출처로 합치는 구조가 아니기 때문에 관리가 복잡해질 수 있다. selectedItems는 items에서 파생된 데이터이므로 별도로 상태로 관리하지 않는 것이 더 적합하다.

개선 방법:
```tsx
const [items, setItems] = useState<Item[]>([]);
const selectedItems = items.filter((item) => item.isSelected);
```
