### ISSUE TITLE
해당 코드가 개선이 필요한 이유와 개선방법을 말해주세요.

### ISSUE THREAD

**Issue by kwonhygge** [deep-dive-everything/typescript-with-react#45]
📚 307p - 309p
📌 해당 코드가 개선이 필요한 이유와 개선방법을 말해주세요.
(objectWillNotChange는 시간이 지나도 변하지 않는 값입니다.)

```tsx
const TestContext = createContext<{
  state: { name: string; age: number } | null;
} | null>(null);

export const useTestContext = () => useContext(TestContext);

export const TestProvider = ({ children }: PropsWithChildren) => {
  const [state, setState] = useState<{
    name: string;
    age: number;
  } | null>(null);

  useEffect(() => {
    const objectWillNotChange = {
      name: "John Doe",
      age: 20,
    };

    setState(objectWillNotChange);
  }, []);

  return (
    <TestContext.Provider
      value={{state}}
    >
      {children}
    </TestContext.Provider>
  );
};
```

**Comment by kwonhygge** [comment]
여기서 context의 value로 들어간 objectWillNotChange 객체는 렌더링될때마다 새로운 객체 인스턴스가 생성되고 매번 다른 객체로 인식되어 불필요한 리렌더링이 발생할 수 있습니다. 따라서 useRef를 사용하여 객체의 참조를 동일하게 유지할 수 있도록 수정해주어야 합니다.
```ts
const store = useRef<Store>(null);

if(!store.current){
  store.current = new Store();
}
```

**Comment by devsomda** [comment]
context의 value로 들어간 objectWillNotChange는 렌더링될 때마다 새로운 객체 인스턴스를 생성해서 매번 다른 객체로 인식된다. 이로 인해 Context를 사용하는 하위 컴포넌트들이 불필요하게 리렌더링되는 문제가 생길 수 있다. 이를 해결하려면 useRef를 사용해서 객체의 참조를 고정하면 된다.

예를 들어, useRef로 객체를 초기화해서 동일한 참조를 유지하도록 바꾸면 된다.

```tsx
const store = useRef<Store>(null);

if (!store.current) {
  store.current = new Store();
}
```
이렇게 하면 store는 렌더링이 반복되어도 동일한 객체를 참조하므로, 불필요한 리렌더링을 방지할 수 있다.


(cf. useMemo도 사용할 수 있지만, 객체 참조 동일성을 유지하기 위해서 useMemo를 사용하는 것은 권장되는 방법이 아니다.)

**Comment by frogk** [comment]
context의 value로 들어간 objectWillNotChange 객체는 렌더링 시마다 새로운 객체가 생성되어 매번 다른 객체로 인식되면서 불필요한 리렌더링이 발생할 수 있습니다. 이를 방지하려면 useRef를 활용해 객체 참조를 유지하도록 수정해야 합니다.

```tsx
const store = useRef<Store>(null);

if (!store.current) {
  store.current = new Store();
}

**Comment by hotdog1004** [comment]
context의 value인 objectWillNotChange는 렌더링될 때마다 새로운 객체 인스턴스가 생성되고 이는 매번 다른 객체로 인식됩니다. 따라서 불필요한 리렌더링이 발생할 수 있습니다. 이를 해결하기 위해 useRef를 사용하여 객체 참조를 유지할 수 있도록 바꾸는 방법이 있습니다.

```tsx
const store = useRef<Store>(null);

if (!store.current) {
  store.current = new Store();
}
```
