### ISSUE TITLE
코드에서 발생하는 문제의 원인과 개선점을 알려주세요. 

### ISSUE THREAD

**Issue by samseburn** [deep-dive-everything/typescript-with-react#47]
📚 309p - 311p
📌 아래 코드에서 initialEmail prop의 값이 변경되어도 화면에서 입력창에 입력된 텍스트의 변화가 없습니다. 발생하는 문제의 원인이 무엇이고, 코드를 어떻게 개선하면 좋을지 작성해주세요.

```tsx
import { useState } from 'react'

type UserEmailProps = {
  initialEmail: string
}

const UserEmail = ({ initialEmail }: UserEmailProps) => {
  const [email, setEmail] = useState(initialEmail)
	
  const onChangeEmail = (event: React.ChangeEvent<HTMLInputElement>) => {
    setEmail(event.target.value)
  }
	
  return (
    <div>
	<input type="text" value={email} onChange={onChagneEmail} />
    </div>
  )
}
```

**Comment by kwonhygge** [comment]
useState의 초깃값으로 설정한 값은 컴포넌트가 마운트될때 한번만 initialEmail 값으로 설정되며 이후에는 독자적으로 관리되기 때문입니다.
이 경우엔 UserEmail에서 관리하던 상태를 부모 컴포넌트로 옮겨서 email 데이터의 출처를 props 하나로 통일할 수 있습니다.

```tsx
import React, { useState } from 'react';

type UserEmailProps = {
  email: string;
  setEmail: React.Dispatch<React.SetStateAction<string>>;
};

const UserEmail: React.VFC<UserEmailProps> = ({ email, setEmail }) => {
  const onChangeEmail = (event: React.ChangeEvent<HTMLInputElement>) => {
    setEmail(event.target.value);
  };
  return (
          <div>
            <input type='text' value={email} onChange={onChangeEmail} />
          </div>
  );
};  
```

**Comment by hotdog1004** [comment]
위 코드는 부모에게서 전달받은 initialEmail으로 email의 초기값을 세팅하고 있습니다. 이 경우 useState의 초깃값으로 설정한 값은 컴포넌트가 마운트될 때 한번만 설정이 되며 그 이후에는 독자적으로 관리됩니다. 
코드를 개선하기 위해 상태를 끌어올려 단일한 출처에서 데이터를 사용하도록 변경할 수 있습니다. UserEmail에서 관리하던 상태를 부모 컴포넌트로 옮겨서 email 데이터의 출처를 props 하나로 통일할 수 있습니다.
```tsx
import React, { useState } from 'react';

// 기존 UserEmail에서 관리하던 상태를 아래와 같이 
// 부모 컴포넌트로 옮겨서 email 데이터의 출처를 props 하나로 통일
type UserEmailProps = {
  email: string;
  setEmail: React.Dispatch<React.SetStateAction<string>>;
};

const UserEmail: React.VFC<UserEmailProps> = ({ email, setEmail }) => {
  const onChangeEmail = (event: React.ChangeEvent<HTMLInputElement>) => {
    setEmail(event.target.value);
  };
  return (
    <div>
      <input type='text' value={email} onChange={onChangeEmail} />
    </div>
  );
};
```

**Comment by frogk** [comment]
useState의 초깃값으로 설정한 값은 컴포넌트가 마운트 될 때 한번만 email의 상태값으로 설정되며 이후에는 독자적으로 관리되기 때문입니다.
상태 끌어올리기로 단일한 출처에서 데이터를 사용하도록 변경해야합니다. UserEmail에서 관리하던 상태를 부모 컴포넌트로 옮겨서 email데이터의 출처를 props 하나로 통일할 수 있습니다.

```tsx
import React, { useState } from 'react';

type UserEmailProps = {
  email: string;
  setEmail: React.Dispatch<React.SetStateAction<string>>;
};

const UserEmail: React.VFC<UserEmailProps> = ({ email, setEmail }) => {
  const onChangeEmail = (event: React.ChangeEvent<HTMLInputElement>) => {
    setEmail(event.target.value);
  };
  return (
    <div>
      <input type='text' value={email} onChange={onChangeEmail} />
    </div>
  );
};

**Comment by devsomda** [comment]
useState의 초깃값으로 설정한 값은 컴포넌트가 마운트될 때 한 번만 email 상태의 값으로 설정되며 이후에는 독자적으로 관리된다. 
useEffect를 사용한 해결책을 떠올렸는데, 좋은 방법이 아닌 이유는 아래와 같다.

1. 의도하지 않은 비동기 처리 문제
useEffect는 비동기로 실행되므로, 상태 초기화가 완료되기 전에 컴포넌트가 렌더링된다. 이로 인해 초기 렌더링 시점에서 email 상태가 undefined나 null처럼 초기화되지 않은 상태일 수 있다. 이는 컴포넌트가 예상치 못한 동작을 하게 만들 수 있다.

```tsx
useEffect(() => {
  setEmail(initialEmail); // 이 동작은 비동기로 처리됨
}, [initialEmail]);
```
초기 렌더링 시점에 email 값이 없는 상태에서 하위 컴포넌트나 로직이 동작하면 버그로 이어질 수 있다.

2. 불필요한 리렌더링
useEffect를 사용해 상태를 설정하면 상태 변경을 트리거하기 때문에 초기 렌더링 이후 한 번 더 리렌더링이 발생한다. 이는 성능 저하를 유발할 수 있다.

```tsx
useEffect(() => {
  setEmail(initialEmail);
}, [initialEmail]);
```
위 코드는 컴포넌트가 렌더링된 후 setEmail로 상태가 변경되면서 추가적인 렌더링을 일으킨다. 초기 상태를 useState로 설정하면 이런 추가적인 렌더링을 방지할 수 있다.

3. 의도하지 않은 동작 가능성
useEffect가 실행되는 타이밍에 따라, initialEmail이 변경되면 불필요하게 상태를 다시 설정할 수도 있다. 초기값만 설정하려는 의도와 다르게 동작하게 되어, 버그로 이어질 수 있다.

따라서, 단일 출처에서 데이터를 사용하도록 변경해야 한다. 
일반적으로 상위 컴포넌트에서 상태를 관리하도록 해주는 상태 끌어올리기를 통해 문제를 해결 한다.
