### ISSUE TITLE
CSS-in-JS와 인라인 스타일의 차이점을 말해주세요

### ISSUE THREAD

**Issue by kwonhygge** [deep-dive-everything/typescript-with-react#48]
📚 328p - 330p
📌 CSS-in-JS와 인라인 스타일의 차이점을 말해주세요

**Comment by limejin** [comment]
인라인 스타일은 HTML태그 style 속성에 직접 스타일을 작성하는 방식을 의미하고 CSS-in-JS는 JavaScript 파일 내에서 CSS를 정의하고 이를 동적으로 <style> 태그로 삽입하는 방법을 의미한다.

**Comment by samseburn** [comment]
인라인 스타일은 HTML 요소의 style 속성을 통해 스타일을 적용하는 방식으로, 간단하지만 CSS 기능이 제한적이며 스타일 재사용이 어렵습니다. 

CSS-in-JS는 자바스크립트를 사용해 스타일을 정의하는 방식으로, 동적 스타일링, CSS 전처리기 기능, 클래스명 해시화를 통해 스타일 충돌 방지 등이 가능합니다. 대표 라이브러리로 styled-components, emotion 등이 있습니다.
