### ISSUE TITLE
CSS-in-JS의 장점 5가지를 간단하게 나열해주세요

### ISSUE THREAD

**Issue by frogk** [deep-dive-everything/typescript-with-react#50]
📚 329p-330p
📌 CSS-in-JS의 장점 5가지를 간단하게 나열해주세요

**Comment by limejin** [comment]
컴포넌트로 생각할 수 있어 별도의 스타일 시트를 유지보수할 필요없이 각 컴포넌트 스타일 관리가 가능하다.
부모요소에서 자동적으로 상속을 받지 않아 부모와 독립적으로 동작한다.
CSS로 컴파일 될 때, 고유한 이름은 만들어 스코프가 생성되기에 선택자 충돌을 방지한다.
자동 벤더 프리픽스가 붙어 브라우저 호환성이 보장된다.
자바스크립트와 CSS 사이 상수와 함수 공유가 가능하다.

**Comment by samseburn** [comment]
- 고유한 클래스명을 자동 생성하여 스타일 충돌 방지
- 컴포넌트 상태나 propr에 따라 동적 스타일링 가능
- CSS와 로직 통합으로 높은 응집도 제공 
- 트리쉐임킹을 통해 성능 최적화
- 전역 스타일, 다크 모드 등의 테마 관리 용이
