### ISSUE TITLE
CSS-in-JS가 등장하게 된 배경에 대해 설명해주세요.

### ISSUE THREAD

**Issue by limejin** [deep-dive-everything/typescript-with-react#51]
📚 331p
📌 CSS-in-JS가 등장하게 된 배경(CSS의 문제점)에 대해 설명해주세요.

**Comment by limejin** [comment]
글로벌 네임스페이스, 의존성, 불필요한 코드 제거 어려움, 클래스 이름 최소화 어려움, 상수 공유 불가능, CSS 로드 순서 따라 달라지는 스타일 우선순위, 외부 수정 관리 어려움.

**Comment by samseburn** [comment]
CSS-in-JS는 CSS의 아래와 같은 문제점을 해소하기 위해 등장했습니다.

- 글로벌 네임스페이스로 클래스 충돌 발생
- 동적 스타일링 구현이 어려움
- 스코프 관리 부족으로 유지보수 어려움
- 컴포넌트와 스타일이 분리되어 관리 복잡도 증가
- 죽은 코드 제거 어려움으로 번들 크기 증가
