### ISSUE TITLE
모노레포가 무엇인지 설명하고 모노레포로 프로젝트를 관리할때의 장점과 단점을 설명해주세요

### ISSUE THREAD

**Issue by frogk** [deep-dive-everything/typescript-with-react#52]
📚 359 - 360p
📌 모노레포가 무엇인지 설명하고 모노레포로 프로젝트를 관리할때의 장점과 단점을 설명해주세요

**Comment by limejin** [comment]
모노레포란 버전 관리 시스템에서 여러 프로젝트를 하나의 레포지토리로 통합하여 관리하는 소프트웨어 개발전략이다. 하나의 레포지토리로 통합하여 관리하기에 불필요한 코드 중복이 줄어들고 공통 모듈도 동일한 프로젝트에서 관리되므로 기능 변화를 쉽게 추적하고 의존성을 관리할 수 있다는 장점이 있다. 단점은 레포지토리가 거대해지는 점, 하나의 레포지토리에 여러 이해관계가 얽힐 수 있다는 점이 있다.

**Comment by samseburn** [comment]
모노레포는 여러 프로젝트를 하나의 저장소에서 관리하는 방식입니다. 주로 대규모 애플리케이션이나 라이브러리에서 공통 코드를 공유하고 버전을 통합 관리할 때 사용합니다.

모노레포는 코드 재사용이 줄어들고 일괄성 있게 의존성을 관리할 수 있다는 장점이 있지만, 복잡한 초기 설정과 프로젝트 규모가 커지면 커질수록 빌드 속도가 필연적으로 증가한다던가, 공통 패키지에 대한 프로젝트의 의존성이 충돌될 수 있다는 단점이 있습니다.
