### ISSUE TITLE
벤더 프리픽스란 무엇인가요?

### ISSUE THREAD

**Issue by devsomda** [deep-dive-everything/typescript-with-react#53]
📚 330p
📌 벤더 프리픽스란 무엇인가요?

**Comment by limejin** [comment]
브라우저 호환 가능하도록 CSS 속성에 추가되는 접두사를 의미합니다. ex.webkit

**Comment by samseburn** [comment]
벤더 프리픽스는 각 브라우저마다 특정 CSS 속성을 표준으로 채택되기 전에 미리 지원하기 위해 사용하는 접두사입니다. 
- `-webkit-`: Chrome, Safari, 최신 버전의 Opera 및 Edge, 거의 모든 iOS 브라우저(iOS용 Firefox), 기본적으로 모든 WebKit 및 Chromium 기반 브라우저
- `-moz-`: Firefox
- `-o-`: WebKit 이전의 오래된 Opera 버전
- `-ms-`: 인터넷 익스플로러 및 Chromium 이전 Microsoft Edge
