### ISSUE TITLE
앰비언트 타입이란 무엇인가요?

### ISSUE THREAD

**Issue by devsomda** [deep-dive-everything/typescript-with-react#54]
📚 338p
📌 앰비언트 타입이란 무엇인가요?

**Comment by limejin** [comment]
값을 포함하는 일반적인 선언과 구별하기 위해 .d.ts 확장자를 가진 파일에서 하는 타입 선언을 의미한다.

**Comment by samseburn** [comment]
앰비언트 타입은 타입스크립트가 외부 환경(자바스크립트 라이브러리, 전역 변수 등)의 타입 정보를 알도록 돕는 선언입니다. 주로 `.d.ts` 파일에서 주로 선언하며, `declare` 키워드를 사용하여 선언도 가능합니다. 원칙적으로 해당 파일 및 키워드 내에서는 타입 선언만 가능합니다. 앰비언트 타입을 통해 타입 안전성을 유지하면서 기존 코드를 사용할 수 있습니다.
