### ISSUE TITLE
증분 컴파일은 무엇이며, 스크립트에서 어떤 옵션을 통해 설정할 수 있나요?

### ISSUE THREAD

**Issue by limejin** [deep-dive-everything/typescript-with-react#55]
📚 350p - 351p
📌 증분 컴파일은 무엇이며, 스크립트에서 어떤 옵션을 통해 설정할 수 있나요?

**Comment by limejin** [comment]
전체를 컴파일하는 것이 아닌 변경이 있는 부분만 컴파일 하는 것의 의미, incremental 옵셤으로 활성화 가능하다.

**Comment by samseburn** [comment]
증분 컴파일은 이전에 컴파일한 결과를 재사용하여 컴파일 성능을 개선하는 기법입니다. 코드가 변경된 부분만 다시 컴파일하고, 이미 컴파일된 부분은 재사용하기 때문에 전체 컴파일 시간을 단축시킬 수 있습니다.

증분 컴파일을 활성화하려면 `tsconfig.json`에서 `incremental` 옵션을 true로 설정하면 됩니다. 

```tsx
{
  "compilerOptions": {
    "incremental": true
  }
}
```
