### ISSUE TITLE
타입스크립트에 unknown 타입이 추가된 이유가 무엇일까요?

### ISSUE THREAD

**Issue by kwonhygge** [deep-dive-everything/typescript-with-react#6]
📚 84p - 85p
📌 타입스크립트에 unknown 타입이 추가된 이유가 무엇일까요?

**Comment by hotdog1004** [comment]
unknown 타입은 any 타입과 유사하지만 타입 검사를 강제하고 타입이 식별된 후에 사용할 수 있기 때문에 any 타입보다 안전하다. 데이터 구조를 파악하기 힘들 때 any 타입을 통해 문제를 임시적으로 회피할 수 있다. 하지만 추후에 any 타입을 특정 타입으로 수정하지 않을 경우 런타임에 예상치 못한 버그가 발생할 수 있다. unknown 타입은 이런 상황을 보완하기 위해 추가되었다.

**Comment by kwonhygge** [comment]
unknown 타입은 any 타입과 유사하게 모든 타입의 값이 할당될 수 있지만 어떤 타입이 할당되었는지 알 수 없음을 나타내기 때문에 값을 가져오거나 내부 속성에 접근할 수 없다. 개발자가 임시로 사용했다가 수정을 깜박하는 등의 실수를 방지하기 위해 unknown 타입이 추가되었다.

**Comment by devsomda** [comment]
unkwown는 any 타입처럼 어떤 타입의 값이든 할당할 수 있다. 하지만 any와 달리 호출 시 에러가 발생해, 예상치 못한 버그를 미리 수정할 수 있다. (즉, 타입 검사를 강제하는 의도를 담고 있다.)

**Comment by limejin** [comment]
any 타입과 유사하지만 any 타입을 사용하면 따르는 예상치 못한 버그 발생률을 줄이기 위해 등장했다. 타입 검사를 강제하고 타입이 식별된 후에 사용할 수 있기에 any 타입보다 안전하다.

**Comment by samseburn** [comment]
타입 안정성을 강화하면서도 any 타입의 유연성을 유지하기 위함입니다. unknown은 기존의 any 타입과 유사하게 어떤 값이든 할당할 수 있지만, 값을 사용하기 전에 타입을 명시적으로 확인해야만 하는 특징이 있습니다. 이를 통해 예상치 못한 에러를 방지할 수 있습니다.
