### ISSUE TITLE
배열과 튜플의 차이점은 무엇인가요?

### ISSUE THREAD

**Issue by devsomda** [deep-dive-everything/typescript-with-react#9]
📚 90p - 91p
📌 배열과 튜플의 차이점은 무엇인가요? (튜플의 특징을 설명해 주세요.)

**Comment by hotdog1004** [comment]
타입스크립트에서 배열은 명시적인 타입 선언을 통해 해당 타입의 원소를 관리하는 것을 강제한다. 하지만 배열의 크기는 제한하지 않는다.
튜플은 배열 기능에 길이 제한까지 추가된 타입시스템이다. 원소 개수와 타입을 보장하기 때문에 더욱 더 안정적인 타입 안정성을 제공한다.

**Comment by kwonhygge** [comment]
배열 타입을 명시하는 것만으로 배열의 길이까지는 제한할 수 없지만 튜플 타입을 사용하면 배열의 길이까지 제한할 수 있습니다.

**Comment by devsomda** [comment]
튜플은 배열의 특정 인덱스에 정해진 타입을 선언하는 것과 같습니다.
예를 들어
let tuple: [number, string, boolean] = [1, "string", true]와 같이 사용할 수 있습니다.

**Comment by limejin** [comment]
튜플은 배열 타입의 하위 타입이다. 기존 배열 기능에 길이 제한까지 추가되어있다. 이를 통해 원소 개수와 타입을 보장하여 배열 원소의 명확한 의미와 쓰임을 보장하여 안전성을 높인다.

**Comment by samseburn** [comment]
배열은 동일한 타입의 요소들이 길이의 제한 없이 나열된 자료 구조이고, 튜플은 정해진 길이와 각 위치에 고정된 타입을 가진 배열입니다. 
배열은 모든 요소가 동일한 타입이어야 하지만, 튜플은 요소마다 다른 타입을 가질 수 있습니다.
